#!/bin/bash -l
#SBATCH --job-name k32trial0_dev
#SBATCH --output=k32trial0_dev/outputs/%a.out
#SBATCH --error=k32trial0_dev/outputs/%a.err
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task 6
#SBATCH --partition=overcap
#SBATCH --constraint=a40
#SBATCH --account=overcap
#SBATCH -a 1-251
#SBATCH --requeue

export PYTHONPATH=.
source ~/.bashrc
conda activate gptj-gpu

train_data=../data/ChemuRef_v3/lm_trimmed_data/train/k32/trial0.jsonl
test_data=../data/ChemuRef_v3/lm_trimmed_data/test_small_predicted_anaphors.jsonl
exp_dir=k32trial0_dev
num_prompts=256

sid=$SLURM_ARRAY_TASK_ID
test_id=$(sed "${sid}q;d" $exp_dir/test_examples.txt) # this can be generated by running scripts/generate_examples_txt.py

python inference/gpt_j_variableNumInContext.py $exp_dir $train_data $test_data $test_id $num_prompts